name: Nix
on:
  pull_request:
  push:
    paths:
      - 'flake.lock'
      - 'flake.nix'

jobs:
  check_flake:
    name: Check Flake
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
    - run: nix flake check
